### PR TITLE
Fix Swedish strings

### LINKED ISSUE #11: Corrections to the Swedish-language UI strings
Corrections to the Swedish-language UI strings in the file app/src/main/res/values-sv/strings.xml .

`<string name="accept_terms_button_enable">Börja använd</string>`
should be
`<string name="accept_terms_button_enable">Börja använda</string>`

`<string name="accept_terms_voluntary_title">Appen är inte oblikatorisk</string>`
should be
`<string name="accept_terms_voluntary_title">Appen är inte obligatorisk</string>`

`<string name="code_entry_en_disabled">Meddelanden om exponering är inte på Gå tillbaka till hem-vyn där du kan koppla på dem</string>`
should be
`<string name="code_entry_en_disabled">Meddelanden om exponering är inte på. Gå tillbaka till hem-vyn där du kan koppla på dem.</string>`

### PR DESCRIPTION
**Pull request by hugovk**
Fixes https://github.com/THLfi/koronavilkku-android/issues/11.

### CODE REVIEW

**Comment by hugovk** [comment]
Passing CI build on my fork: https://github.com/hugovk/koronavilkku-android/actions/runs/232729401

**Comment by hugovk** [comment]
Merge conflict resolved.

**Comment by hugovk** [comment]
@solita-alperttiti Is it so that you cannot accept language corrections via PR? Should I close this?

See also https://github.com/THLfi/koronavilkku-android/pull/27 and https://github.com/THLfi/koronavilkku-android/pull/29.

**Comment by ghost** [comment]
This has been fixed in 8c79064. Thank you for contributing it!

**Pull request closed without merging**
